import type { NextPage } from "next";
import Head from "next/head";
import MainFirst from "./MainFirst";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>SelfCheck</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainFirst />
    </div>
  );
};

export default Home;
